version: 2

references:

  ubuntu_deps: &ubuntu_deps
    run:
      name: Install dependencies on Ubuntu.
      command: |
        apt-get update -qy
        apt-get install -y git python3-dev python3-pip
  
  arch_deps: &arch_deps
    run:
      name: Install dependencies on Arch Linux.
      command: |
        pacman -S --noconfirm python python-pip git base-devel
  
  install: &install
    run:
      name: Install.
      command: |
        pip3 install .

  test: &test
    run:
      name: Run tests.
      command: |
        python3 setup.py test

  deploy: &deploy
    deploy:
      name: PyPI deploy
      command: |
        pip3 install wheel setuptools --upgrade
        bash ./.circleci/.circle_pypi_deploy.sh

jobs:
            
  test_ubuntu_latest:
    docker:
      - image: ubuntu:latest
      - image: rethinkdb
    working_directory: ~/cxflow-rethinkdb
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_ubuntu_rolling:
    docker:
      - image: ubuntu:rolling
      - image: rethinkdb
    working_directory: ~/cxflow-rethinkdb
    steps:
      - *ubuntu_deps
      - checkout
      - *install
      - *test

  test_archlinux:
    docker:
      - image: pritunl/archlinux:2017-07-08
      - image: rethinkdb
    working_directory: ~/cxflow-rethinkdb
    steps:
      - *arch_deps
      - checkout
      - *install
      - *test
      - *deploy

workflows:

  version: 2
  test-matrix:
    jobs:
      - test_ubuntu_latest
      - test_ubuntu_rolling
      - test_archlinux
